#!/usr/bin/env bash
# The T executor (PROTOCOL.md §19): run every (source, tree, destination)
# job through a fixed pool of workers. One job = one sendtree invocation
# over ssh; per-host batching (sendall) is gone, so jupiter's three
# destinations run concurrently while a small host's no-op sails past.
#
#   stevedore-orchestrate.sh [--serial] [--workers N]
#
# Config vocabulary (generated by fleetrun.sh):
#   [orchestrator-jobs]     one row per job:
#       <source-id> <user@host> <remote-conf> <tree> <dest-id> <dial>
#   [orchestrator-workers]  pool size (default 8; --workers overrides)
#
# Three stages:
#   1. snapshot-pre : every unique (source, tree) takes the run snapshot
#      once, idempotently, BEFORE any transfer -- concurrent jobs of one
#      tree can never double-snap or race the snapshot into existence.
#   2. fan-out      : the worker pool. Scheduler (owner-specified, do not
#      "improve"): when a slot frees, sort outstanding jobs by destination
#      load (running jobs against that destination), then by source load
#      (running jobs on that source), pick the top. Ties fall wherever the
#      scan's determinism puts them -- explicitly fine.
#   3. prune-post   : a tree is pruned on its source only after ALL of
#      that tree's destinations finished clean (sendtree --prune-only);
#      receiver-side pruning stays at ENDTREE as always.
#
# Failure policy: a job exiting 3 (no session ever) kills its
# (source, dest) pair for the run; ssh 255 kills the source. Remaining
# jobs on a dead pair/source are skipped, not attempted.
#
# Output modes:
#   * interactive (stderr is a tty): live board, ONE LINE PER WORKER,
#     repainted in place; per-job output goes to log files, failing jobs
#     get their tails dumped at the end.
#   * headless: plain parallel, line-interleaved (each line carries its
#     [src]>[dest] prefix from the remote side).
#   * --serial: one job at a time, full scrolling output.
#
# Exit: 0 all jobs ok,
#       1 hard failures (unreachable hosts, snapshot failures, dead
#         pairs/sources and the jobs skipped because of them),
#       2 every job ran, but some datasets inside failed (sendtree rc=2).

set -euo pipefail
here="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
source "$here/stevedore-cfgparser.sh"
source "$here/stevedore-ec2helpers.sh"

# One orchestrate/deploy at a time across the estate.
orch_lock

serial=""
workers="${orchworkers:-8}"
while (( $# > 0 )); do
    case "$1" in
        --serial)  serial=1; shift ;;
        --workers) workers="${2:-}"; shift 2 ;;
        *) echo "Usage: $0 [--serial] [--workers N]" >&2; exit 64 ;;
    esac
done
if ! [[ "$workers" =~ ^[0-9]+$ && "$workers" -ge 1 ]]; then
    echo "ERROR: bad worker count '$workers'" >&2
    exit 64
fi

#
# ---------- job table ---------------------------------------------------------
#
J_SRC=(); J_SSH=(); J_RCONF=(); J_TREE=(); J_DST=(); J_DIAL=()
for entry in "${orchjobs[@]}"; do
    read -r src sshd rconf tree dst dial _ <<<"$entry"    # ignore extra columns
    if [[ -z "${dial:-}" ]]; then
        echo "ERROR: malformed [orchestrator-jobs] row: $entry" >&2
        exit 78
    fi
    J_SRC+=( "$src" ); J_SSH+=( "$sshd" ); J_RCONF+=( "$rconf" )
    J_TREE+=( "$tree" ); J_DST+=( "$dst" ); J_DIAL+=( "$dial" )
done
njobs=${#J_SRC[@]}
if (( njobs == 0 )); then
    if [[ ${#orchtargets[@]} -gt 0 ]]; then
        echo "ERROR: [orchestrator-targets] host mode was retired by T (PROTOCOL.md §19);" >&2
        echo "       run through fleetrun.sh, which generates [orchestrator-jobs]." >&2
        exit 78
    fi
    echo "No jobs in [orchestrator-jobs]; nothing to do." >&2
    exit 0
fi

# Per-job state:
#   J_STATE  pending | running | done | skipped
#   J_RC     numeric exit for done jobs
#   J_WHY    human reason for skipped / non-zero jobs
J_STATE=(); J_RC=(); J_WHY=(); J_T0=(); J_SECS=()
for (( i = 0; i < njobs; i++ )); do
    J_STATE[i]="pending"; J_RC[i]=""; J_WHY[i]=""; J_T0[i]=""; J_SECS[i]=""
done
declare -A src_load=() dest_load=()      # identity -> currently running jobs
declare -A dead_src=() dead_pair=()      # "src" / "src|dst" -> poisoned this run
pids=()
logdir=""
QUIET=""                                 # live board: defer per-job messages

# One snapshot name for the whole run, every source, every tree -- same
# format sendall used, so the prune prefix and existing tooling all match.
snap="stevedore-$(date -u +%Y-%m-%d-%H%MZ)"

job_label() {   # $1 = job index -> "[src] tree -> [dst]"
    printf '[%s] %s -> [%s]' "${J_SRC[$1]}" "${J_TREE[$1]}" "${J_DST[$1]}"
}

# The remote command for one job. run_indented is a sourced function, not
# an executable, hence the bash -c wrapper; the prefix names both ends so
# nothing downstream tags the stream again. $2 is extra env for the
# sudo env invocation (" STEVEDORE_COLS=N" under the live board).
# The [ -t 2 ] probe MUST happen here, before run_indented wraps stderr
# in the gawk pipe: cfgparser's own tty check runs inside that pipe and
# would never see the pty, so pv would stay silent for the whole run
# (sendall used to probe at the right moment; found on the first real T
# run when three massive sends showed no progress at all).
job_cmd() {
    printf "sudo -n env STEVEDORE_CONF=%s STEVEDORE_DEST_ID=%s%s bash -c '[ -t 2 ] && export PV_FORCE_FLAG=-f; source ${STEVE_LIB}/stevedore-run-indented.sh; run_indented \"[%s]>[%s] \" ${STEVE_LIB}/stevedore-sendtree.sh --no-prune %s@%s %s'" \
        "${J_RCONF[$1]}" "${J_DST[$1]}" "$2" "${J_SRC[$1]}" "${J_DST[$1]}" \
        "${J_TREE[$1]}" "$snap" "${J_DIAL[$1]}"
}

# Owner-specified scheduler. Scans pending jobs; result in PICKED (-1 if
# none runnable). NOT a $(...) helper on purpose: it also retires jobs
# whose pair/source died, and a subshell would lose those state changes.
PICKED=-1
pick_job() {
    PICKED=-1
    local i d s bd=0 bs=0 src dst
    for (( i = 0; i < njobs; i++ )); do
        [[ "${J_STATE[i]}" == "pending" ]] || continue
        src="${J_SRC[i]}"; dst="${J_DST[i]}"
        if [[ -n "${dead_src[$src]:-}" ]]; then
            J_STATE[i]="skipped"; J_WHY[i]="source dead this run"
            continue
        fi
        if [[ -n "${dead_pair["$src|$dst"]:-}" ]]; then
            J_STATE[i]="skipped"; J_WHY[i]="(source, dest) pair dead this run"
            continue
        fi
        d=${dest_load[$dst]:-0}
        s=${src_load[$src]:-0}
        if (( PICKED < 0 || d < bd || ( d == bd && s < bs ) )); then
            PICKED=$i; bd=$d; bs=$s
        fi
    done
}

mark_running() {   # $1 = job index
    J_STATE[$1]="running"
    J_T0[$1]=$(date +%s)
    src_load[${J_SRC[$1]}]=$(( ${src_load[${J_SRC[$1]}]:-0} + 1 ))
    dest_load[${J_DST[$1]}]=$(( ${dest_load[${J_DST[$1]}]:-0} + 1 ))
}

on_job_finish() {   # $1 = job index, $2 = rc
    local i="$1" rc="$2"
    local src="${J_SRC[i]}" dst="${J_DST[i]}"
    src_load[$src]=$(( ${src_load[$src]:-1} - 1 ))
    dest_load[$dst]=$(( ${dest_load[$dst]:-1} - 1 ))
    J_STATE[i]="done"
    J_RC[i]="$rc"
    J_SECS[i]=$(( $(date +%s) - ${J_T0[i]:-$(date +%s)} ))
    case $rc in
        0)  : ;;
        2)  J_WHY[i]="some datasets failed"
            [[ -n "$QUIET" ]] || echo "NOTE: $(job_label "$i") completed, but some datasets failed" >&2 ;;
        3)  J_WHY[i]="no session to destination"
            dead_pair["$src|$dst"]=1
            [[ -n "$QUIET" ]] || echo "ERROR: $(job_label "$i"): no session; pair is dead for this run" >&2 ;;
        255) J_WHY[i]="ssh to source failed"
            dead_src[$src]=1
            [[ -n "$QUIET" ]] || echo "ERROR: $(job_label "$i"): ssh failed; source is dead for this run" >&2 ;;
        *)  J_WHY[i]="sendtree rc=$rc"
            [[ -n "$QUIET" ]] || echo "ERROR: $(job_label "$i"): sendtree exited rc=$rc" >&2 ;;
    esac
}

# Last visual record of a log: pv separates in-place updates with \r, so
# split on both \r and \n and take the final non-blank record -- exactly
# what the bottom line of a serial terminal would be showing.
latest_line() {
    tail -c 4096 "$1" 2>/dev/null | tr '\r' '\n' | grep -v '^[[:space:]]*$' | tail -n 1 || true
}

# Per-job log path, named for humans (owner-specified order): the tree
# names the workload, slashes flattened; the job index is a postfix
# uniquifier only.
job_log() {   # $1 = job index
    printf '%s/%s-%s-%s-%s.log' "$logdir" "${J_SRC[$1]}" "${J_DST[$1]}" "${J_TREE[$1]//\//_}" "$1"
}

orch_cleanup() {
    local p
    for p in "${pids[@]}"; do kill "$p" 2>/dev/null || true; done
    tput cnorm 2>/dev/null || true
    stop_ec2_instances
}

ec2_maybe_start
# ec2_maybe_start installed its own EXIT trap; replace it with a combined
# handler so an interrupt also reaps the ssh children and restores the
# cursor before the instances are stopped.
trap orch_cleanup EXIT

#
# ---------- stage 1: snapshot-pre ----------------------------------------------
#
# One idempotent recursive snapshot per unique (source, tree), all before
# any transfer: the || fallback tolerates a same-minute rerun that already
# made it (see sendall's history in PROTOCOL.md §18). A failure here fails
# every job of that tree up front; ssh 255 declares the source dead.
echo "run snapshot: @$snap" >&2
declare -A snapdone=()       # "src|tree" -> ok | failed
for (( i = 0; i < njobs; i++ )); do
    src="${J_SRC[i]}"; tree="${J_TREE[i]}"; key="$src|$tree"
    [[ -z "${snapdone[$key]:-}" ]] || continue
    if [[ -n "${dead_src[$src]:-}" ]]; then
        snapdone[$key]="failed"
        continue
    fi
    echo "snapshot-pre: [$src] $tree@$snap" >&2
    set +e
    ssh "${ssh_opts[@]}" "${J_SSH[i]}" \
        "sudo -n sh -c 'zfs snapshot -r $tree@$snap 2>/dev/null || zfs list -H $tree@$snap >/dev/null 2>&1'" \
        </dev/null
    src_rc=$?
    set -e
    if (( src_rc == 255 )); then
        echo "ERROR: [$src] unreachable; skipping all its jobs" >&2
        dead_src[$src]=1
        snapdone[$key]="failed"
    elif (( src_rc != 0 )); then
        echo "ERROR: snapshot-pre failed on [$src]: $tree@$snap" >&2
        snapdone[$key]="failed"
    else
        snapdone[$key]="ok"
    fi
done
for (( i = 0; i < njobs; i++ )); do
    key="${J_SRC[i]}|${J_TREE[i]}"
    if [[ "${J_STATE[i]}" == "pending" && "${snapdone[$key]}" != "ok" ]]; then
        if [[ -n "${dead_src[${J_SRC[i]}]:-}" ]]; then
            J_STATE[i]="skipped"; J_WHY[i]="source unreachable"
        else
            J_STATE[i]="done"; J_RC[i]=1; J_WHY[i]="snapshot failed"
        fi
    fi
done

#
# ---------- stage 2: fan-out (the pool) -----------------------------------------
#
# One engine for both parallel modes. Live: per-job logs, one repainted
# board line per WORKER, remote pty pinned to a width frozen once per run
# (clamped to 132 so the logs stay readable in narrower viewers later;
# STEVEDORE_COLS overrides). Plain: raw line-interleaved output, each line
# already prefixed remotely.
run_pool() {   # $1 = live | plain
    local mode="$1" w i rc running pending content
    local slot_job=() slot_pid=()
    for (( w = 0; w < workers; w++ )); do slot_job[w]=""; slot_pid[w]=""; done

    local c_run=$'\e[36m' c_off=$'\e[0m'
    local cols=0 prev_cols=0 remote_cols=0
    if [[ "$mode" == "live" ]]; then
        QUIET=1
        logdir=$(mktemp -d /tmp/stevedore-orch.XXXXXX)
        cols=$(tput cols 2>/dev/null) || cols=120
        prev_cols=$cols
        local wire_cols="${STEVEDORE_COLS:-$(( cols < 132 ? cols : 132 ))}"
        remote_cols=$(( wire_cols > 40 ? wire_cols - 2 : wire_cols ))
        echo "fan-out: $njobs jobs across $workers workers (logs: $logdir)" >&2
        for (( w = 0; w < workers; w++ )); do printf '\n' >&2; done
        tput civis 2>/dev/null || true
    fi

    while :; do
        # reap finished slots
        for (( w = 0; w < workers; w++ )); do
            i="${slot_job[w]}"
            [[ -n "$i" ]] || continue
            if ! kill -0 "${slot_pid[w]}" 2>/dev/null; then
                set +e
                wait "${slot_pid[w]}"
                rc=$?
                set -e
                on_job_finish "$i" "$rc"
                slot_job[w]=""
                slot_pid[w]=""
            fi
        done

        # refill free slots from the scheduler
        for (( w = 0; w < workers; w++ )); do
            [[ -z "${slot_job[w]}" ]] || continue
            pick_job
            i=$PICKED
            (( i >= 0 )) || break
            mark_running "$i"
            if [[ "$mode" == "live" ]]; then
                ssh -tt "${ssh_opts[@]}" "${J_SSH[i]}" \
                    "stty cols $remote_cols 2>/dev/null || true; exec $(job_cmd "$i" " STEVEDORE_COLS=$remote_cols")" \
                    </dev/null >"$(job_log "$i")" 2>&1 &
            else
                echo "job start: $(job_label "$i")" >&2
                ssh "${ssh_opts[@]}" "${J_SSH[i]}" "$(job_cmd "$i" "")" </dev/null &
            fi
            slot_pid[w]=$!
            slot_job[w]="$i"
            pids+=( "$!" )
        done

        running=0
        for (( w = 0; w < workers; w++ )); do
            [[ -n "${slot_job[w]}" ]] && running=1
        done
        pending=0
        for (( i = 0; i < njobs; i++ )); do
            [[ "${J_STATE[i]}" == "pending" ]] && pending=1
        done

        if [[ "$mode" == "live" ]]; then
            cols=$(tput cols 2>/dev/null) || cols=120
            if (( cols != prev_cols )); then
                # Width changed: the old region may have rewrapped, making
                # the cursor-up arithmetic lie. Abandon it, re-anchor below.
                prev_cols=$cols
                for (( w = 0; w < workers; w++ )); do printf '\n' >&2; done
            fi
            printf '\e[%dA' "$workers" >&2
            for (( w = 0; w < workers; w++ )); do
                i="${slot_job[w]}"
                if [[ -n "$i" ]]; then
                    content=$(latest_line "$(job_log "$i")")
                    [[ -n "$content" ]] || content="starting $(job_label "$i")..."
                    # budget: "▸ " takes 2 columns; the longest remote line
                    # is cols-3 (pty pinned to cols-2, pv shrunk one more),
                    # so cols-3 of content shows pv's full line -- total
                    # cols-1, still never touching the last column. cols-4
                    # here used to clip pv's final character (the ETA digit).
                    printf '\e[2K%s %s\n' "${c_run}▸${c_off}" "${content:0:cols > 3 ? cols - 3 : 1}" >&2
                else
                    printf '\e[2K· %s\n' "idle" >&2
                fi
            done
        fi

        (( running || pending )) || break
        sleep 0.2
    done

    if [[ "$mode" == "live" ]]; then
        tput cnorm 2>/dev/null || true
        # (The receiver-only-snapshot NOTE reprint lived here until
        # 2026-07-31 -- retired with the NOTE itself; unknown-since
        # stamps + gc tracking carry that signal now.)
        # keep the logs if anything went sideways, and show the tails
        local any_bad=0
        for (( i = 0; i < njobs; i++ )); do
            [[ "${J_STATE[i]}" == "done" && "${J_RC[i]}" != "0" ]] && any_bad=1
        done
        if (( any_bad )); then
            for (( i = 0; i < njobs; i++ )); do
                if [[ "${J_STATE[i]}" == "done" && "${J_RC[i]}" != "0" ]]; then
                    echo "---- $(job_label "$i") last lines (full log: $(job_log "$i")) ----" >&2
                    # strip the pty's CRLF first, then split pv's bare-\r
                    # records; tr alone would double-space every line
                    sed -e 's/\r$//' "$(job_log "$i")" | tr '\r' '\n' | tail -n 40 >&2
                fi
            done
            echo "Per-job logs kept in: $logdir" >&2
        else
            rm -rf -- "$logdir"
        fi
    fi
}

# --serial: one job at a time in scheduler order, output scrolling straight
# to the terminal (a tty on stderr gets pv progress via ssh -t).
run_serial() {
    local tty_flag=() i rc
    [[ -t 2 ]] && tty_flag=( -t )
    while :; do
        pick_job
        i=$PICKED
        (( i >= 0 )) || break
        mark_running "$i"
        echo "job: $(job_label "$i")" >&2
        set +e
        ssh "${tty_flag[@]}" "${ssh_opts[@]}" "${J_SSH[i]}" "$(job_cmd "$i" "")"
        rc=$?
        set -e
        on_job_finish "$i" "$rc"
    done
}

if [[ -n "$serial" ]]; then
    run_serial
elif [[ -t 2 ]]; then
    rows=$(tput lines 2>/dev/null) || rows=50
    if (( workers + 3 > rows )); then
        echo "NOTE: terminal too short for the live board ($workers workers); using plain output." >&2
        run_pool plain
    else
        run_pool live
    fi
else
    run_pool plain
fi

#
# ---------- stage 3: prune-post --------------------------------------------------
#
# A tree is pruned on its source only when every one of its destinations
# finished clean: pruning after a partial run could destroy the very
# snapshot a failed destination needs as its incremental base next time.
declare -A pp_rep=() pp_clean=()
pp_keys=()
for (( i = 0; i < njobs; i++ )); do
    key="${J_SRC[i]}|${J_TREE[i]}"
    if [[ -z "${pp_rep[$key]:-}" ]]; then
        pp_rep[$key]=$i
        pp_clean[$key]=1
        pp_keys+=( "$key" )
    fi
    if [[ "${J_STATE[i]}" != "done" || "${J_RC[i]}" != "0" ]]; then
        pp_clean[$key]=""
    fi
done
for key in "${pp_keys[@]}"; do
    i=${pp_rep[$key]}
    if [[ -z "${pp_clean[$key]}" ]]; then
        echo "NOTE: not pruning [${J_TREE[i]}] on [${J_SRC[i]}]: not every destination finished clean" >&2
        continue
    fi
    echo "prune-post: [${J_TREE[i]}] on [${J_SRC[i]}]" >&2
    # Headless: the per-snapshot prune lines print inline (prefixed), so
    # whatever captures the run -- a cron unit's journal, a redirect --
    # has them. Live board: the screen stays clean and the lines go
    # nowhere; the result is inspectable on the source itself.
    # STEVEDORE_SHOW_PRUNES=1 promotes them to the board runs too.
    if [[ -n "$QUIET" && -z "${STEVEDORE_SHOW_PRUNES:-}" ]]; then
        ssh "${ssh_opts[@]}" "${J_SSH[i]}" \
            "sudo -n env STEVEDORE_CONF=${J_RCONF[i]} $STEVE_LIB/stevedore-sendtree.sh --prune-only ${J_TREE[i]}" \
            </dev/null >/dev/null 2>&1 \
            || echo "WARNING: prune-post failed for [${J_TREE[i]}] on [${J_SRC[i]}]" >&2
    else
        ssh "${ssh_opts[@]}" "${J_SSH[i]}" \
            "sudo -n env STEVEDORE_CONF=${J_RCONF[i]} bash -c 'source $STEVE_LIB/stevedore-run-indented.sh; run_indented \"[${J_SRC[i]}] \" $STEVE_LIB/stevedore-sendtree.sh --prune-only ${J_TREE[i]}'" \
            </dev/null \
            || echo "WARNING: prune-post failed for [${J_TREE[i]}] on [${J_SRC[i]}]" >&2
    fi
done

#
# ---------- summary ---------------------------------------------------------------
#
oks=(); parts=(); hards=(); skips=()
for (( i = 0; i < njobs; i++ )); do
    case "${J_STATE[i]}" in
        skipped) skips+=( "$(job_label "$i") (${J_WHY[i]})" ) ;;
        done)
            case "${J_RC[i]}" in
                0) oks+=( "$(job_label "$i")" ) ;;
                2) parts+=( "$(job_label "$i")" ) ;;
                *) hards+=( "$(job_label "$i") (${J_WHY[i]:-rc=${J_RC[i]}})" ) ;;
            esac ;;
        *) hards+=( "$(job_label "$i") (never ran)" ) ;;
    esac
done

if [[ ${#oks[@]} -gt 0 ]]; then
    echo "Fully successful:" >&2
    printf '  %s\n' "${oks[@]}" >&2
fi
if [[ ${#parts[@]} -gt 0 ]]; then
    echo "Completed with some failed datasets:" >&2
    printf '  %s\n' "${parts[@]}" >&2
fi
if [[ ${#skips[@]} -gt 0 ]]; then
    echo "Skipped (dead pair or source):" >&2
    printf '  %s\n' "${skips[@]}" >&2
fi
if [[ ${#hards[@]} -gt 0 ]]; then
    echo "Failed jobs:" >&2
    printf '  %s\n' "${hards[@]}" >&2
fi
printf 'run summary: %d jobs, %d ok, %d with failed datasets, %d failed, %d skipped\n' \
    "$njobs" "${#oks[@]}" "${#parts[@]}" "${#hards[@]}" "${#skips[@]}" >&2

# One JSON line per job -- the run report's raw feed (PROTOCOL.md §22).
# The system ledger dir when install made it writable, the state dir
# otherwise; failure to record is never allowed to fail the run. Field
# values are all from the fixed identity/tree/why vocabularies, so no
# JSON escaping games.
report_dir="$STEVE_VAR"
if ! mkdir -p "$report_dir" 2>/dev/null || [[ ! -w "$report_dir" ]]; then
    report_dir="${XDG_STATE_HOME:-$HOME/.local/state}/stevedore"
    mkdir -p "$report_dir" 2>/dev/null || report_dir=""
fi
if [[ -n "$report_dir" ]]; then
    report_ts=$(date -u +%Y-%m-%dT%H:%M:%SZ)
    for (( i = 0; i < njobs; i++ )); do
        # failed-dataset drilldown: harvested from the job log when one
        # exists (live board keeps logs of failing jobs); headless runs
        # leave the FAILED-DATASETS line in the journal instead.
        fdl=""
        wbl=0
        if [[ -n "$logdir" && -f "$(job_log "$i")" ]]; then
            fdl=$(grep -a "FAILED-DATASETS:" "$(job_log "$i")" 2>/dev/null | tail -n 1 | sed -e 's/\r$//' -e 's/.*FAILED-DATASETS: //') || fdl=""
            # receiver-reported wire bytes (2.1); 0 when absent/2.0
            wbl=$(grep -a "WIRE-BYTES:" "$(job_log "$i")" 2>/dev/null | tail -n 1 | sed -e 's/\r$//' -e 's/.*WIRE-BYTES: //') || wbl=0
            [[ "$wbl" =~ ^[0-9]+$ ]] || wbl=0
        fi
        printf '{"ts":"%s","snap":"%s","src":"%s","tree":"%s","dst":"%s","state":"%s","rc":"%s","why":"%s","failed_ds":"%s","bytes":%s,"secs":%s}\n' \
            "$report_ts" "$snap" "${J_SRC[i]}" "${J_TREE[i]}" "${J_DST[i]}" \
            "${J_STATE[i]}" "${J_RC[i]:-}" "${J_WHY[i]:-}" "$fdl" "$wbl" "${J_SECS[i]:-0}"
    done >> "$report_dir/runs.jsonl" 2>/dev/null || true
fi

if [[ ${#hards[@]} -gt 0 || ${#skips[@]} -gt 0 ]]; then
    exit 1
fi
if [[ ${#parts[@]} -gt 0 ]]; then
    exit 2
fi
